server:
  port: 8084
spring:
#  main: # <-- ДОБАВЬ ЭТУ СЕКЦИЮ
#    allow-circular-references: false # <-- РАЗРЕШАЕМ ЦИКЛЫ
  application:
    name: selmag-feedback-service

  kafka: # <-- Kafka здесь - ПРАВИЛЬНО
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    bootstrap-servers: localhost:9092

  boot: # <-- Теперь под spring
    admin:
      client:
        url: http://localhost:8085
        instance:
          name: feedback-service
          service-host-type: ip
        enabled: false # изменил для ухода от цкл зависимсти

  cloud: # <-- Теперь под spring
    config:
      enabled: false # <-- Теперь Spring увидит эту настройку

  data: # <-- Теперь под spring
    mongodb:
      uri: mongodb://localhost:27017/feedback

  security: # <-- Теперь под spring
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8082/realms/selmag
      client:
        registration:
          keycloak:
            client-id: feedback-service
            client-secret: 4cD79sTpV318BqiIWWUYsfjywdzg4DeK
            authorization-grant-type: client_credentials
            scope:
              - metrics_server
          discovery:
            provider: keycloak
            client-id: feedback-service
            client-secret: 4cD79sTpV318BqiIWWUYsfjywdzg4DeK
            authorization-grant-type: client_credentials
            scope:
              - discovery
        provider:
          keycloak:
            issuer-uri: http://localhost:8082/realms/selmag

# --- Свойства вашего приложения ---
app:
  kafka:
    topic:
      product-reviews: product-reviews
      favourite-products-events: favourite-products-events
# ---------------------------------

springdoc:
  swagger-ui:
    oauth:
      client-id: feedback-service-swagger-ui
      use-pkce-with-authorization-code-grant: true
keycloak:
  uri: http://localhost:8082
management:
  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  client:
    enabled: false